[package]
name = "lnsr"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "GPL-2.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
